import { Listing, Testimonial } from "./types";

// April Zhao's real transactions from MLS
export const listings: Listing[] = [
  {
    id: "23",
    address: "1220 Irwin St",
    city: "Belmont, CA 94002",
    price: 1888000,
    bedrooms: 3,
    bathrooms: 1.5,
    sqft: 1490,
    status: "pending",
    images: ["/images/1220_Irwin_St.jpg"],
    description: "Single family home in Belmont.",
    yearBuilt: 1947,
    propertyType: "Single Family",
    mlsLink: "https://www.redfin.com/CA/Belmont/1220-Irwin-St-94002/home/1801223",
  },
  {
    id: "1",
    address: "176 Waters Park Cir",
    city: "San Mateo, CA 94403",
    price: 1310000,
    bedrooms: 2,
    bathrooms: 2.5,
    sqft: 1602,
    status: "sold",
    images: ["/images/176_waters_park_cir.jpeg"],
    description: "Welcome to 176 Waters Park Circle, a modern townhouse in San Mateo's vibrant Marina Lagoon neighborhood. Built in 2021, this beautifully maintained home offers 2 beds & 2.5 baths, and 1,602 sqft of thoughtfully designed living space. The open-concept main level seamlessly connects the living, dining, and kitchen areas, creating an inviting atmosphere ideal for both entertaining and everyday living. The chef-inspired kitchen features top-of-the-line appliances, sleek countertops, and ample cabinetry for the modern cook. Enjoy a balcony off the main living area that extends your living space outdoors, perfect for morning coffee or evening relaxation. Upstairs, two spacious bedrooms offer comfort and privacy. The primary suite boasts a generous walk-in closet, an elegant en-suite bathroom, and its own private balcony for a quiet retreat. Thoughtful upgrades include owned solar panels, an EV charger, and luxury vinyl flooring throughout (except stairs). Additional highlights include in-unit laundry, central A/C, and an attached two-car tandem garage for convenience and storage. Ideally located near parks, shopping, dining, and major highways, this home combines modern design, energy efficiency, and a prime San Mateo location - offering the perfect balance of style and everyday ease.",
    yearBuilt: 2021,
    soldDate: "Dec 22, 2025",
    propertyType: "Townhouse",
    mlsLink: "https://www.mlslistings.com/property/ml82018709/176-waters-park-cir-san-mateo-ca-94403/17238304",
    mlsNumber: "ML82018709",
    hoaFees: 350,
    garage: "Attached Garage, Tandem Parking, 2 Car(s)",
    heating: "Central Forced Air",
    cooling: "Ceiling Fan, Central Forced Air",
    features: [
      "Island with Sink",
      "Pantry",
      "Kitchen/Family Room Combo",
      "Dining Area",
      "Shingle Roof",
      "Slab Foundation",
    ],
    appliances: [
      "Cooktop - Electric",
      "Dishwasher",
      "Garbage Disposal",
      "Microwave",
      "Oven - Built-In",
      "Refrigerator",
      "Washer/Dryer",
    ],
    schools: {
      elementary: "San Mateo-Foster City Elementary",
      highSchool: "San Mateo Union High",
    },
  },
  {
    id: "2",
    address: "2042 23rd Ave",
    city: "San Francisco, CA 94116",
    price: 3018000,
    bedrooms: 3,
    bathrooms: 3.5,
    sqft: 2718,
    status: "sold",
    images: ["/images/2042_23rd_Ave.jpg"],
    description: "Step into this meticulously renovated, unique, redesigned split-level home has been transformed from top to bottom, offering an unparalleled living experience for those with a taste for sophisticated design. The main level features a fluid, open-concept layout that guide you through a bright, sun-drenched living room with a sleek, minimalist fireplace. The space flows seamlessly into the dining area and the heart of the home: a chef's kitchen that will inspire your inner culinary artist. This state-of-the-art kitchen is equipped with high-end stainless steel appliances, custom cabinetry, pantry, a large center island, and designer finishes. The home's thoughtful split-level design creates a private, serene retreat on each floor. The upper level is home to a tranquil and expansive primary suite, complete with a generous walk-in closet and a spa-like ensuite bath. This private sanctuary also offers a walk-out to a private deck. Two well-appointed bedrooms (2nd master bed), and a hall full bathroom offering both convenience and privacy. The 4th room currently configured a home office, which could be easily converted into a fourth bedroom. Outside, the large, professionally landscaped backyard is an urban sanctuary, offering a private oasis for al fresco dining and entertaining.",
    yearBuilt: 1941,
    soldDate: "Nov 26, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/sf425074363/2042-23rd-ave-san-francisco-ca-94116/17279962",
    mlsNumber: "SF425074363",
    garage: "Attached Garage, Tandem Parking, 1 Car(s)",
    heating: "Central Forced Air",
    cooling: "None",
    features: [
      "Electric Fireplace",
      "Wood Flooring",
      "Updated Bath(s)",
      "Split-Level Design",
      "Landscaped Backyard",
    ],
    appliances: [
      "Dishwasher",
      "Garbage Disposal",
      "Microwave",
      "Oven Range - Built-In",
      "Gas",
      "Dryer",
      "Washer",
    ],
  },
  {
    id: "3",
    address: "1830 Vera Ave",
    city: "Redwood City, CA 94061",
    price: 2220000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 1470,
    status: "sold",
    images: ["/images/1830_Vera_Ave.jpeg"],
    description: "Welcome to this stunning 3-bedroom, 2-bathroom home that's been fully remodeled from top to bottom with designer high-end finishes. A huge bonus is the 360 additional sqft with the detached ADU, featuring an additional bedroom, full kitchen and bathroom. Ideal for guests, extended family, or rental income potential. Enjoy the comfort of brand-new flooring, recessed lighting, and stylish fixtures throughout. Step inside to an open-concept floor plan that seamlessly connects the living, dining, and kitchen areas. This home is perfect for entertaining or relaxing with family. The modern kitchen features sleek cabinetry, quartz countertops, stainless steel appliances, and a spacious island with bar seating. The primary suite offers a private retreat with an elegant en-suite bath and generous closet space.",
    yearBuilt: 1948,
    soldDate: "Nov 17, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/ml82024902/1830-vera-ave-redwood-city-ca-94061/17324369",
    mlsNumber: "ML82024902",
    garage: "Off-Street Parking, Parking Area, No Garage",
    heating: "Central Forced Air",
    cooling: "Central Forced Air",
    features: [
      "Detached ADU",
      "Hardwood Flooring",
      "Fireplace Insert",
      "Kitchen/Family Room Combo",
      "Primary Suite with Walk-in Closet",
      "Composition Roof",
    ],
    appliances: [
      "Cooktop - Gas",
      "Garbage Disposal",
      "Microwave",
      "Oven Range - Gas",
      "Refrigerator",
    ],
    schools: {
      elementary: "Redwood City Elementary",
      highSchool: "Sequoia Union High",
    },
  },
  {
    id: "4",
    address: "241 Shelford Ave",
    city: "San Carlos, CA 94070",
    price: 2000000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1780,
    status: "sold",
    images: ["/images/241_Shelford_Ave.jpeg"],
    description: "This inviting 3-bedroom, 2-bathroom home offers a thoughtful floor plan with timeless appeal. A formal entry opens to the spacious living room with dining area, large picture windows and a cozy fireplace. The open-concept kitchen and family room feature a breakfast bar and direct access to the private patio. The primary suite with dual closets is tucked down the hall, while two additional bedrooms share a full hall bathroom. An attached two-car garage provides convenient parking, extra storage, and includes laundry facilities. Located in highly sought-after San Carlos, this home is served by top-rated schools and is just moments from the vibrant downtown restaurants and shops. Enjoy nearby parks, scenic hiking trails, and easy access to streamlined commute routes.",
    yearBuilt: 1960,
    soldDate: "Oct 31, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/ml82023418/241-shelford-ave-san-carlos-ca-94070/17301979",
    mlsNumber: "ML82023418",
    garage: "Attached Garage, Off-Street Parking, 2 Car(s)",
    heating: "Central Forced Air",
    cooling: "None",
    features: [
      "Living Room Fireplace",
      "Separate Family Room",
      "Dining Bar",
      "Eat-in Kitchen",
      "Private Patio",
      "Metal Roof",
      "Laundry in Garage",
    ],
    schools: {
      elementary: "San Carlos Elementary",
      highSchool: "Sequoia Union High",
    },
  },
  {
    id: "5",
    address: "435 Voelker Dr",
    city: "San Mateo, CA 94403",
    price: 2000000,
    bedrooms: 4,
    bathrooms: 2,
    sqft: 2250,
    status: "sold",
    images: ["/images/435_Voelker_Dr.jpeg"],
    description: "Don't let this one pass you by. So much to offer in an outstanding location. Imagine being able to walk to elementary, middle school, and high school, Beresford Park, or even Hillsdale Mall from this wonderful westside home. This bright and inviting split level home has everything you are looking for: space to entertain, relax in the garden, work from home, and cozy up in front of the fire. 4 Bedrooms and 2 baths plus a versatile bonus room provide so many options for living and working. The large, fenced in backyard offers privacy and beauty with mature trees and low maintenance landscaping. Eat in kitchen with great views of the yard with separate dining room area or flex space. Floor to ceiling windows in the living room offer sunlight and scenery of the surrounding San Mateo area. Because the home sits uniquely on a \"drive\" not a thoroughfare, traffic is minimal. You will love living here. Welcome home to Voelker Drive!",
    yearBuilt: 1953,
    soldDate: "Oct 27, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/ml82020534/435-voelker-dr-san-mateo-ca-94403/17263384",
    mlsNumber: "ML82020534",
    garage: "Attached Garage, 2 Car(s)",
    heating: "Forced Air",
    cooling: "None",
    features: [
      "Split Level Design",
      "Living Room Fireplace",
      "Formal Dining Room",
      "Eat-in Kitchen",
      "Bonus Room",
      "Hardwood Flooring",
      "Large Fenced Backyard",
      "Composition Shingle Roof",
      "Laundry in Garage",
    ],
    appliances: [
      "Dishwasher",
      "Exhaust Fan",
      "Oven Range - Electric",
      "Refrigerator",
      "Washer/Dryer",
    ],
    schools: {
      elementary: "San Mateo-Foster City Elementary",
      highSchool: "San Mateo Union High",
    },
  },
  {
    id: "6",
    address: "1214 North Rd",
    city: "Belmont, CA 94002",
    price: 2528000,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2550,
    status: "sold",
    images: ["/images/1214_North_Rd.jpeg"],
    description: "Wow! Sweeping, panoramic views of the Bay from the San Mateo Bridge, to the Bay Bridge, downtown San Francisco, and the hills beyond! This extensively updated home is flooded with natural light and designed to make the most of its setting, with vaulted ceilings and wide-view windows that keep the skyline front and center. Two primary suites - each with walk-in closets and spacious bathrooms - give you options for flexibility and privacy. The eat-in kitchen flows to a large entertaining patio with two seating areas and a sleek modern fire pit, perfect for dinners that stretch late into the evening. On the view deck you will find a hot tub and seating area overlooking the Bay, setting the stage for unforgettable nights. Inside, there's room to spread out with a bonus oversized family room and wine cave, plus plenty of storage throughout. A formal dining area, gleaming hardwood floors, attached two-car garage, and paver driveway add convenience and style. Extensive upgrades are found throughout the home, including a Tesla solar system on the roof. Tucked into the Belmont hills, the home offers privacy and access to top-rated schools, all while being just minutes from everything the Peninsula has to offer.",
    yearBuilt: 1977,
    soldDate: "Oct 9, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/ml82020316/1214-north-rd-belmont-ca-94002/17260773",
    mlsNumber: "ML82020316",
    garage: "Attached Garage, Gate/Door Opener, 2 Car(s)",
    heating: "Central Forced Air",
    cooling: "Central Forced Air",
    features: [
      "Panoramic Bay Views",
      "Two Primary Suites",
      "Vaulted Ceilings",
      "Gas Burning Fireplace",
      "Separate Family Room",
      "Wine Cave",
      "Hardwood Flooring",
      "Spa/Hot Tub",
      "Tesla Solar System",
      "Contemporary Style",
      "Formal Dining Room",
    ],
    appliances: [
      "Dishwasher",
      "Exhaust Fan",
      "Garbage Disposal",
      "Microwave",
      "Oven Range - Gas",
      "Refrigerator",
      "Dryer",
      "Washer",
    ],
    schools: {
      elementary: "Belmont-Redwood Shores Elementary",
      highSchool: "Sequoia Union High",
    },
  },
  {
    id: "7",
    address: "3530 Altamont Way",
    city: "Redwood City, CA 94062",
    price: 2266000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1525,
    status: "sold",
    images: ["/images/3530_Altamont_Way.jpeg"],
    description: "Blending timeless style with modern comfort, this beautifully reimagined 3-bedroom, 2-bath home offers an exceptional lifestyle in a coveted neighborhood with scenic views. Spanning 1,525 sq. ft. on a 7,051 sq. ft. lot, the home has been thoughtfully remodeled with designer finishes and a flowing layout ideal for both everyday living and entertaining. The striking contemporary entry opens to light-filled interiors, including a designer eat-in kitchen with quartz countertops, tile backsplash, stainless steel appliances, pantry, and sliding doors to the front deck. An elegant dining area showcases sweeping views, while the expansive living room features hardwood floors and a dramatic tiled fireplace. The luxurious primary suite boasts a spa-like bath with double vanity, rain shower, and mosaic tile accents. A serene backyard retreat offers composite decking, lush lawn, fruit trees, and mature landscaping. Additional highlights include an oversized 550 sq. ft. garage, dual pane windows, Tesla charger, Nest thermostat, & air conditioning. Ideally located near parks, recreation, downtown, and top-rated Roy Cloud School.",
    yearBuilt: 1960,
    soldDate: "Sep 30, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/ml82020462/3530-altamont-way-redwood-city-ca-94062/17262516",
    mlsNumber: "ML82020462",
    garage: "Attached Garage, 2 Car(s)",
    heating: "Central Forced Air - Gas",
    cooling: "Central Forced Air",
    features: [
      "Scenic Views",
      "Wood Burning Fireplace",
      "Hardwood & Tile Flooring",
      "Quartz Countertops",
      "Spa-like Primary Bath",
      "Tesla Charger",
      "Nest Thermostat",
      "Dual Pane Windows",
      "Composite Deck",
      "Fruit Trees",
    ],
    appliances: [
      "Cooktop - Electric",
      "Dishwasher",
      "Refrigerator",
    ],
    schools: {
      elementary: "Redwood City Elementary",
      highSchool: "Sequoia Union High",
    },
  },
  {
    id: "8",
    address: "2325 Hastings Dr",
    city: "Belmont, CA 94002",
    price: 2308888,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 2210,
    status: "sold",
    images: ["/images/2325_Hastings_Dr.jpeg"],
    description: "Tucked away in the serene hills of Belmont, this beautifully updated home spans two levels and showcases sweeping views of the San Francisco Bay and surrounding canyons. A gated entry leads you along a private path into a charming courtyard. Double doors open to the main level, where a warm and inviting living room connects to the formal dining area. The space flows seamlessly into an updated kitchen and a spacious family room - where breathtaking panoramic views of the Bay and canyon unfold before you. Step out onto the rear patio to fully take in the scenery. Upstairs, the expansive primary suite features a private balcony with unobstructed views, a walk-in closet, and an elegant en-suite bath. Two additional generously sized bedrooms share a naturally bright hall bathroom. Nestled in a sought-after Peninsula neighborhood, this home is centrally located near top-rated Belmont schools, Carlmont Village Shopping Center, the public library, and major highways. This is a rare opportunity to enjoy modern comfort, spectacular views, and a prime Peninsula location all in one exceptional home.",
    yearBuilt: 1977,
    soldDate: "Sep 16, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/ml82016778/2325-hastings-dr-belmont-ca-94002/17210394",
    mlsNumber: "ML82016778",
    garage: "Detached, 2 Car(s)",
    heating: "Gas",
    cooling: "Window/Wall Unit",
    features: [
      "Panoramic Bay Views",
      "Canyon Views",
      "Gated Entry",
      "Courtyard",
      "Living Room Fireplace",
      "Formal Dining Room",
      "Separate Family Room",
      "Primary Suite Balcony",
      "Walk-in Closet",
      "Two-Level Layout",
    ],
    schools: {
      elementary: "Belmont-Redwood Shores Elementary",
      highSchool: "Sequoia Union High",
    },
  },
  {
    id: "9",
    address: "1735 Terrace Dr",
    city: "Belmont, CA 94002",
    price: 2600000,
    bedrooms: 5,
    bathrooms: 4,
    sqft: 2800,
    status: "sold",
    images: ["/images/1735_Terrace_Dr.jpeg"],
    description: "Welcome to 1735 Terrace Drive, a unique hillside retreat nestled in one of Belmont's most desirable family-friendly neighborhoods. This exceptional home blends luxury, comfort, and cutting-edge energy efficiency all with breathtaking south-facing views from nearly every room. Tesla Powerwall + 15 New Solar Panels (NEM 2.0 plan) - say goodbye to electric bills, PG&E often pays you! Heat pump-based heating & A/C with Smart Meter. New Dual Pane Windows for optimal energy efficiency. Top-Rated Belmont Public Schools (Award-Winning Elementary, Middle & High). Close to UC's New Innovation Campus (Notre Dame de Namur campus to be developed by the University of California). Minutes to Downtown Belmont, Caltrain, and Highway 101 & 280. Friendly, safe, and vibrant community atmosphere.",
    yearBuilt: 1956,
    soldDate: "Aug 27, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/ml82013563/1735-terrace-dr-belmont-ca-94002/17164007",
    mlsNumber: "ML82013563",
    garage: "Attached Garage, 2 Car(s)",
    heating: "Central Forced Air, Heat Pump, Solar",
    cooling: "Central Forced Air",
    features: [
      "South-Facing Views",
      "Tesla Powerwall",
      "15 Solar Panels (NEM 2.0)",
      "Heat Pump HVAC",
      "Smart Meter",
      "Dual Pane Windows",
      "Living Room Fireplace",
      "Separate Family Room",
      "Laundry in Garage",
    ],
    schools: {
      elementary: "Belmont-Redwood Shores Elementary",
      highSchool: "Sequoia Union High",
    },
  },
  {
    id: "10",
    address: "2310 Wooster Ave",
    city: "Belmont, CA 94002",
    price: 2300000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 2030,
    status: "sold",
    images: ["/images/2310_Wooster_Ave.jpeg"],
    description: "WELCOME HOME to panoramic city lights and bay views on Wooster Avenue! Enjoy your morning coffee while watching the sun glisten on the water below. Surrounded by lush foliage and native plants, the grounds are well manicured. Meandering pathways lead you to a massive rear sun deck - perfect for stargazing and gathering with friends and family - tucked into a canopy of trees with views for miles. In the middle of it all is a meticulously refreshed home that offers three bedrooms and two baths on the main level with access to a secluded and cozy lower level retreat - equipped with high ceilings, cork floors and a fireplace! 2310 Wooster Avenue sits on a flat section of street with convenient access to all that the mid-peninsula offers. Belmont Schools and quick access to local commute corridors make this home a dream landing spot. Newer windows, and updated mechanical systems including tankless water heater, and owned solar system (NEM 2). Multiple patio spaces for relaxation and entertainment. Screened in porch/Veranda great for kids, easily accessible from primary suite surrounded by native garden offering quiet serenity and a secluded retreat.",
    yearBuilt: 1962,
    soldDate: "Aug 19, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/ml82013886/2310-wooster-ave-belmont-ca-94002/17167885",
    mlsNumber: "ML82013886",
    garage: "Attached Garage, Off-Street Parking, 2 Car(s)",
    heating: "Central Forced Air, Gas",
    cooling: "Whole House Fan",
    features: [
      "Panoramic Bay Views",
      "City Lights Views",
      "Owned Solar System (NEM 2)",
      "Tankless Water Heater",
      "Lower Level Retreat",
      "Living Room Fireplace",
      "Granite Countertops",
      "Skylights",
      "Hardwood & Laminate Flooring",
      "Screened Porch/Veranda",
      "Multiple Patio Spaces",
      "EV Hookup Level 1",
    ],
    appliances: [
      "Cooktop - Electric",
      "Garbage Disposal",
      "Oven Range",
      "Refrigerator",
    ],
    schools: {
      elementary: "Belmont-Redwood Shores Elementary",
      highSchool: "Sequoia Union High",
    },
  },
  {
    id: "11",
    address: "1564 Molitor Rd",
    city: "Belmont, CA 94002",
    price: 2250000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1920,
    status: "sold",
    images: ["/images/1564_Molitor_Rd.jpeg"],
    description: "Spanish Charm in this 3 bedroom 2 bathroom located in the lower hills of Belmont. Approximately 1920 sf nestled on a 6608 sf lot. Built in 1929 and close proximity to shopping, restaurants, seasonal weekly Farmers Market, Twin Pines Park, convenient commuter routes Hwy 101, 92, 280 and the train station. Formal entry with coved ceilings, opens to the step down living room with a picture window overlooking the San Francisco skyline. The formal dining room boasts built-in cabinets and ornate ceiling cast molding. Walls of windows that focus on the stunning views. Sunny breakfast nook and a secluded front porch. The spacious kitchen has been remodeled and is replete with granite counters, double ovens, subway tile backsplash, vaulted open beam ceiling, 5 burner gas cooktop, luxury laminate. Two guest bedrooms and a generous sized primary suite filled with light. Both bathrooms have been remodeled. The side patio leads to the level backyard with multiple entertaining areas.",
    yearBuilt: 1929,
    soldDate: "Aug 4, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/ml82009913/1564-molitor-rd-belmont-ca-94002/17104333",
    mlsNumber: "ML82009913",
    garage: "Attached Garage, Gate/Door Opener, 1 Car(s)",
    heating: "Central Forced Air - Gas",
    cooling: "None",
    features: [
      "Spanish Style",
      "SF Skyline Views",
      "Coved Ceilings",
      "Formal Dining Room",
      "Built-in Cabinets",
      "Ornate Ceiling Molding",
      "Gas Log Fireplace",
      "Breakfast Nook",
      "Vaulted Open Beam Ceiling",
      "Remodeled Kitchen & Baths",
      "Level Backyard",
      "Hardwood & Laminate Flooring",
    ],
    appliances: [
      "Cooktop - Gas (5 Burner)",
      "Dishwasher",
      "Double Oven",
      "Refrigerator",
      "Washer/Dryer",
    ],
    schools: {
      elementary: "Belmont-Redwood Shores Elementary",
      highSchool: "Sequoia Union High",
    },
  },
  {
    id: "12",
    address: "631 Spar Dr",
    city: "Redwood City, CA 94065",
    price: 1900000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1080,
    status: "sold",
    images: ["/images/631_Spar_Dr.jpeg"],
    description: "This charming single-level Ranch-style home offers the perfect balance of a tranquil retreat and everyday convenience. Inside, you'll find a cozy living room with a welcoming fireplace, two guest bedrooms, a full bathroom, and a private main suite with its own en-suite bath. The bright, open-concept kitchen and family room create a seamless flow into the spacious dining area - ideal for both relaxing evenings and entertaining guests. Freshly updated with new interior paint throughout, the home has been meticulously maintained, professionally cleaned, move-in ready. Location is everything, minutes from the scenic Redwood Shores Bay Trail, with easy access to parks, and beautiful walking paths. You're also minutes from Redwood Shores Marketplace, featuring Nob Hill Foods, Starbucks, local restaurants, and the Bay Club fitness center. It's within walking distance to Oracle and offers effortless commuting with quick access to Highway 101 and Downtown San Carlos. Nestled in an especially quiet neighborhood with top-rated schools, this home checks every box.",
    yearBuilt: 1972,
    soldDate: "May 26, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/ml82002708/631-spar-dr-redwood-city-ca-94065/17011430",
    mlsNumber: "ML82002708",
    garage: "Attached Garage, 2 Car(s)",
    heating: "Central Forced Air",
    cooling: "None",
    features: [
      "Single-Level Ranch Style",
      "Living Room Fireplace",
      "Open-Concept Kitchen",
      "Eat-in Kitchen",
      "New Interior Paint",
      "Move-in Ready",
      "Near Bay Trail",
      "Walking Distance to Oracle",
      "Composition Roof",
      "Laundry in Garage",
    ],
    appliances: [
      "Microwave",
      "Oven - Gas",
      "Oven Range",
    ],
    schools: {
      elementary: "Belmont-Redwood Shores Elementary",
      highSchool: "Sequoia Union High",
    },
  },
  {
    id: "13",
    address: "721 Taylor Blvd",
    city: "Millbrae, CA 94030",
    price: 2828000,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 2280,
    status: "sold",
    images: ["/images/721_Taylor_Blvd.jpg"],
    description: "Beautiful split level home located in central Millbrae - It features 3 bedrooms, 2.5 bathrooms, and a spacious family room providing direct access to the backyard area. From the front door, entering into a bright and airy open floor plan showcasing modern finishes throughout - Updated kitchen and bathrooms with luxury built countertops and cabinetries, high-end appliances, expensive hardwood floors throughout. Excellent location - Walk to neighborhood school, park, trail and downtown Millbrae.",
    yearBuilt: 1943,
    soldDate: "May 20, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/sf425031449/721-taylor-blvd-millbrae-ca-94030/17015867",
    mlsNumber: "SF425031449",
    garage: "Attached Garage, Interior Access, Tandem Parking",
    heating: "Central Forced Air, Gas - Natural",
    cooling: "Central Forced Air",
    features: [
      "Split Level Design",
      "Open Floor Plan",
      "Family Room with Skylight",
      "Family Room Fireplace",
      "Living Room Fireplace",
      "Breakfast Nook",
      "Hardwood & Tile Flooring",
      "Updated Kitchen & Baths",
      "Direct Backyard Access",
      "Walk to Downtown Millbrae",
    ],
    appliances: [
      "Cooktop - Gas",
      "Dishwasher",
      "Garbage Disposal",
      "Hood Over Range",
      "Microwave",
      "Oven - Gas",
      "Refrigerator",
      "Dryer",
      "Washer",
    ],
  },
  {
    id: "14",
    address: "1176 Fairview Ave",
    city: "Redwood City, CA 94061",
    price: 2750000,
    bedrooms: 4,
    bathrooms: 3.5,
    sqft: 2010,
    status: "sold",
    images: ["/images/1176_Fairview_Ave.jpeg"],
    description: "Welcome to this beautifully reimagined and entirely rebuilt home, where modern design meets comfort and convenience. With exceptional curb appeal and thoughtfully landscaped front and backyards, this like-new residence offers a bright, open floor plan perfect for today's lifestyle. Step inside to discover a stylish living space featuring two luxurious primary suites on opposite sides of the home, ensuring privacy and flexibility. The spacious open kitchen with a dedicated dining area is perfect for entertaining. Outdoor living shines with fresh turf in the front yard, new sod in the backyard, a charming pond, and garden beds. Enjoy energy efficiency with solar panels and a battery system, plus EV compatibility for added convenience. Minutes from grocery stores, restaurants, and downtown Redwood City. Close to Red Morton Park for outdoor recreation. Don't miss this incredible opportunity to own a turn-key contemporary home in a prime location!",
    yearBuilt: 1949,
    soldDate: "May 6, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/ml81999107/1176-fairview-ave-redwood-city-ca-94061/16969578",
    mlsNumber: "ML81999107",
    garage: "On Street, 2 Car(s)",
    heating: "Central Forced Air",
    cooling: "Central Forced Air",
    features: [
      "Entirely Rebuilt",
      "Two Primary Suites",
      "Open Floor Plan",
      "Kitchen/Family Room Combo",
      "Solar Panels & Battery",
      "EV Compatible",
      "Landscaped Front & Back",
      "Garden Pond",
      "Turn-Key Ready",
      "Near Red Morton Park",
    ],
    schools: {
      elementary: "Redwood City Elementary",
      highSchool: "Sequoia Union High",
    },
  },
  {
    id: "15",
    address: "2850 Belmont Canyon Rd",
    city: "Belmont, CA 94002",
    price: 2950000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2920,
    status: "sold",
    images: ["/images/2850_Belmont_Canyon_Rd.jpeg"],
    description: "This exceptional home boasts breathtaking, framed views of San Francisco, seamlessly blending luxury with tranquility. Designed for both relaxation and entertaining, the expansive 1,000+ sq. ft. deck is a true showstopper, featuring a hot tub, sauna, outdoor shower, built-in kitchen, and a charming cottage connected by a picturesque bridge. Inside, soaring ceilings and transom windows bathe the living room in natural light, offering serene vistas of the surrounding oaks. The dining area flows effortlessly into a chef's kitchen, complete with a spacious island, Thermador gas range, Bosch dishwasher, and an oversized pantry. Modern conveniences abound - wired Ethernet ensures high-speed connectivity, while built-in ceiling speakers and surround sound create an immersive ambiance. The media room is perfect for movie nights or quiet relaxation. The primary suite is a private sanctuary, featuring its own deck, a gas fireplace, dual closets, and a spa-inspired bath with a jetted tub. Sustainability meets convenience with a 2.8 kW solar panel system, Tesla Powerwall, and an EV charger. Ideally located with easy access to Highways 92, 101, and 280, this home offers the perfect balance of seclusion and accessibility.",
    yearBuilt: 1999,
    soldDate: "Apr 28, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/be41088127/2850-belmont-canyon-rd-belmont-ca-94002/16937374",
    mlsNumber: "BE41088127",
    heating: "Gas, Gravity, 2+ Zones",
    cooling: "Multi-Zone",
    features: [
      "San Francisco Views",
      "1,000+ SF Deck",
      "Hot Tub & Sauna",
      "Outdoor Shower",
      "Built-in Outdoor Kitchen",
      "Guest Cottage with Bridge",
      "Gas Fireplace (Family Room & Primary)",
      "Media Room",
      "Soaring Ceilings",
      "Built-in Surround Sound",
      "Wired Ethernet",
      "2.8 kW Solar Panels",
      "Tesla Powerwall",
      "EV Charger",
      "Contemporary Style",
    ],
    appliances: [
      "Built-in BBQ Grill",
      "Microwave",
      "Oven - Self Cleaning",
      "Oven Range - Built-In",
      "Oven Range - Gas (Thermador)",
      "Refrigerator",
      "Dishwasher (Bosch)",
      "Dryer",
      "Washer",
    ],
  },
  {
    id: "16",
    address: "7 Chestnut St",
    city: "San Carlos, CA 94070",
    price: 2200000,
    bedrooms: 4,
    bathrooms: 2.5,
    sqft: 2870,
    status: "sold",
    images: ["/images/7_Chestnut_St.jpeg"],
    description: "Step into 7 Chestnut St, bursting with potential in one of San Carlos' most exclusive neighborhoods. This expansive 2,870-square-foot home features four spacious bedrooms and two and a half bathrooms. Situated on a remarkable 12,838 sf double lot at the top of the hill, indulge in private decks and generous outdoor spaces, perfect for entertaining, relaxing, and soaking in the beauty of your surroundings. With breathtaking east-facing bay views from every room. Its quiet, private location ensures a serene retreat and still connected to everything the city has to offer. Whether you choose to restore its vintage charm or create a contemporary masterpiece, this home provides the ultimate blank canvas to craft your ideal living space. San Carlos is known for its warm and welcoming community, excellent schools, and small-town charm with big-city amenities. A vibrant downtown, where fine dining, charming cafés, and boutique shopping await. Easy access to parks, Trader Joe's, and Highway 101, this home blends privacy, prestige, and convenience.",
    yearBuilt: 1979,
    soldDate: "Apr 1, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/ml81995437/7-chestnut-st-san-carlos-ca-94070/16924488",
    mlsNumber: "ML81995437",
    garage: "Attached Garage, 2 Car(s)",
    heating: "Forced Air, Gas",
    cooling: "None",
    features: [
      "East-Facing Bay Views",
      "12,838 SF Double Lot",
      "Hilltop Location",
      "Private Decks",
      "Wood Burning Fireplace",
      "Formal Dining Room",
      "Separate Family Room",
      "Primary Bedroom on Ground Floor",
      "Spa/Hot Tub",
      "Concrete Roof",
    ],
    appliances: [
      "Oven Range - Gas",
      "Refrigerator",
    ],
    schools: {
      elementary: "San Carlos Elementary",
      highSchool: "Sequoia Union High",
    },
  },
  {
    id: "17",
    address: "503 Sardinia Ter",
    city: "Sunnyvale, CA 94089",
    price: 1780000,
    bedrooms: 3,
    bathrooms: 3.5,
    sqft: 1992,
    status: "sold",
    images: ["/images/503_Sardinia_Ter.jpeg"],
    description: "Modern 5-Year-Old Townhouse with Premium Upgrades! This stunning townhouse features an open floor plan with abundant natural light and high-end finishes. A master suite on the ground floor offers privacy, while a dedicated office space with a built-in desk is perfect for remote work. The modern kitchen boasts quartz countertops, trendy cabinets, and stainless steel appliances. Enjoy the breeze from the balcony with scenic views. Upstairs are two spacious master suites with elegant bathrooms. The home is equipped with a Tesla solar system, Powerwall backup, smart light switches, and motorized shades for select windows. A whole house fan provides immediate cool air on hot summer days, in addition to separate zoned AC. Located near Hi-Tech companies with quick access to Highway 101, 237, and Downtown Sunnyvale.",
    yearBuilt: 2020,
    soldDate: "Mar 11, 2025",
    propertyType: "Townhouse",
    mlsLink: "https://www.mlslistings.com/property/ml81993544/503-sardinia-ter-sunnyvale-ca-94089/16901983",
    mlsNumber: "ML81993544",
    hoaFees: 370,
    garage: "Attached Garage, 2 Car(s)",
    heating: "Central Forced Air - Gas",
    cooling: "Central Forced Air, Multi-Zone",
    features: [
      "5-Year-Old Construction",
      "Open Floor Plan",
      "Ground Floor Master Suite",
      "Dedicated Home Office",
      "Balcony with Views",
      "Tesla Solar System",
      "Tesla Powerwall",
      "Smart Light Switches",
      "Motorized Shades",
      "Whole House Fan",
      "Zoned AC",
      "Tile Roof",
    ],
    appliances: [
      "Washer/Dryer",
    ],
    schools: {
      elementary: "Sunnyvale",
      highSchool: "Fremont Union High",
    },
  },
  {
    id: "18",
    address: "2742 El Sobrante St",
    city: "Santa Clara, CA 95051",
    price: 2200000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1150,
    status: "sold",
    images: ["/images/2742_El_Sobrante_St.jpeg"],
    description: "Don't miss this incredible opportunity to create your dream home! This beautifully updated 3-bedroom, 2-bathroom Single Family House boasts 1,150 square feet of modern living space and sits on a spacious lot with pristine landscaping. The home has been completely renovated with a brand-new kitchen featuring quartz countertop, beautiful island, sleek stainless-steel appliances, and stylish new bathrooms. Enjoy the comfort of a new AC system and a new water heater for year-round convenience. The backyard is a standout, offering newly installed fences, fresh landscaping, and a stunning new patio, perfect for outdoor gatherings. Inside, you'll find updated flooring throughout, along with a layout that includes a spacious primary suite with an attached bathroom. Additional features include newer dual pane windows, an attached 2-car garage, and ample side-yard space ideal for RV or boat parking. This home is centrally located, just 3 miles from Apple Headquarters, and offers easy access to shopping, dining, grocery stores, and more.",
    yearBuilt: 1956,
    soldDate: "Feb 19, 2025",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/ml81990929/2742-el-sobrante-st-santa-clara-ca-95051/16863222",
    mlsNumber: "ML81990929",
    garage: "Attached Garage, 2 Car(s)",
    heating: "Central Forced Air",
    cooling: "None",
    features: [
      "Completely Renovated",
      "Brand-New Kitchen",
      "Quartz Countertops",
      "Kitchen Island",
      "New AC System",
      "New Water Heater",
      "Living Room Fireplace",
      "Dual Pane Windows",
      "New Patio",
      "New Fencing & Landscaping",
      "RV/Boat Parking",
      "3 Miles from Apple HQ",
      "Composition Roof",
    ],
    appliances: [
      "Dishwasher",
      "Oven Range - Gas",
      "Refrigerator",
      "Washer/Dryer",
    ],
    schools: {
      elementary: "Santa Clara Unified",
      highSchool: "Santa Clara Unified",
    },
  },
  {
    id: "19",
    address: "1990 Scott Ln",
    city: "Los Altos, CA 94024",
    price: 3800000,
    bedrooms: 4,
    bathrooms: 2.5,
    sqft: 1868,
    status: "sold",
    images: ["/images/1990_Scott_Ln.jpeg"],
    description: "Situated in the desirable Highlands neighborhood and steps to Montclaire Elementary. An ideal single-level floor plan, lovely grounds with mature trees, the best of indoor-outdoor living & entertaining. Nice pavers pathway that leads past a leveled lawn and through nice plantings to the front entrance. Spacious kitchen and family room with a sliding door leading to the rear grounds with a beautiful pool and a very private outdoor space. Three well-sized bedrooms and the primary suite has gorgeous natural light and a large closet.",
    yearBuilt: 1959,
    soldDate: "Dec 10, 2024",
    propertyType: "Single Family",
    mlsNumber: "ML81985355",
    garage: "Attached Garage, 2 Car(s)",
    heating: "Central Forced Air",
    cooling: "Central Forced Air",
    features: [
      "Single-Level Floor Plan",
      "Highlands Neighborhood",
      "Heated In-Ground Pool",
      "Kitchen/Family Room Combo",
      "Family Room Fireplace",
      "Living Room Fireplace",
      "Gas Starter Fireplace",
      "Hardwood Flooring",
      "Mature Trees",
      "Private Backyard",
      "Wood Roof",
    ],
    schools: {
      elementary: "Cupertino Union",
      highSchool: "Fremont Union High",
    },
  },
  {
    id: "20",
    address: "445 Parrott Dr",
    city: "San Mateo, CA 94402",
    price: 3200000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2020,
    status: "sold",
    images: ["/images/445_Parrott_Dr.jpeg"],
    description: "Welcome to 445 Parrott Drive in sought after Baywood Knolls. This lovingly maintained home has beautiful refinished hardwood floors throughout and has been freshly painted both inside and out. Featuring 4 bedrooms and 3 full baths, the inviting floor plan surrounds a beautiful stone patio and yard. Feel the spaciousness of the vaulted open beam ceiling and floor to ceiling windows of the living room. Enjoy entertaining in the formal dining room with bay window and custom built-in cabinetry. The primary bedroom with open beam ceiling includes a walk-in closet, bath with large tub, stall shower and dual sinks. The updated kitchen with breakfast space features high-end cabinetry, stainless steel appliances, granite counters and large island with sink and built in microwave. A laundry closet with stack washer/dryer finishes the kitchen area. Enjoy the serenity of the lovely rear yard with stone patio, lawn and mature landscaping. Stairs lead up the elevated hillside to the cabana with hot tub. Convenient to downtown San Mateo, Caltrain, and Highways 92, 280 and 101.",
    yearBuilt: 1951,
    soldDate: "Jul 31, 2024",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/ml81970636/445-parrott-dr-san-mateo-ca-94402/16544257",
    mlsNumber: "ML81970636",
    garage: "Attached Garage, Off-Street Parking, 2 Car(s)",
    heating: "Central Forced Air - Gas",
    cooling: "Central Forced Air",
    features: [
      "Baywood Knolls",
      "Vaulted Open Beam Ceilings",
      "Floor to Ceiling Windows",
      "Living Room Fireplace",
      "Formal Dining Room",
      "Bay Window",
      "Custom Built-in Cabinetry",
      "Walk-in Closet",
      "Granite Counters",
      "Kitchen Island with Sink",
      "Hardwood Flooring",
      "Stone Patio",
      "Cabana with Hot Tub",
      "Metal Roof",
      "Contemporary Style",
    ],
    appliances: [
      "Cooktop - Electric",
      "Dishwasher",
      "Exhaust Fan",
      "Ice Maker",
      "Oven - Electric",
      "Oven Range - Built-In",
      "Refrigerator",
      "Dryer",
      "Washer",
    ],
    schools: {
      elementary: "San Mateo-Foster City Elementary",
      highSchool: "San Mateo Union High",
    },
  },
  {
    id: "21",
    address: "3 Kimmie Ct",
    city: "Belmont, CA 94002",
    price: 3450000,
    bedrooms: 5,
    bathrooms: 3,
    sqft: 2430,
    status: "sold",
    images: ["/images/3_Kimmie_Ct.jpeg"],
    description: "This 5-bedroom, 3-bathroom home boasts a recently updated kitchen and bathrooms, flooding the space with natural light. Nestled on a quiet cul-de-sac near hiking trails and the Carlmont shopping center, it offers both convenience and tranquility. Enjoy views from two of the upstairs bedrooms, while the lush English garden ensures privacy. The main level features one bedroom and a full bath, perfect for families or guests. Top rated Belmont Schools and easy access to Highway 92, 101 and 280.",
    yearBuilt: 1967,
    soldDate: "Jul 10, 2024",
    propertyType: "Single Family",
    mlsNumber: "ML81969493",
    garage: "Attached Garage, 2 Car(s)",
    heating: "Forced Air",
    cooling: "None",
    features: [
      "Quiet Cul-de-Sac",
      "Updated Kitchen & Baths",
      "Views from Upstairs Bedrooms",
      "English Garden",
      "Main Level Bedroom & Bath",
      "Wood Burning Fireplace",
      "Kitchen/Family Room Combo",
      "Formal Dining Room",
      "Near Hiking Trails",
      "Composition Roof",
    ],
    appliances: [
      "Cooktop - Electric",
      "Dishwasher",
      "Microwave",
      "Oven Range - Electric",
      "Refrigerator",
      "Washer/Dryer",
    ],
    schools: {
      elementary: "Belmont-Redwood Shores Elementary",
      highSchool: "Sequoia Union High",
    },
  },
  {
    id: "22",
    address: "1017 Avalon Ave",
    city: "Foster City, CA 94404",
    price: 2120000,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 1910,
    status: "sold",
    images: [],
    description: "Best deal on the market! Bright and open, vaulted ceilings greet you when you walk into the formal dining and living room combo. Inviting kitchen, eat-in dining space and cozy family seating area have a view of the quaint and meticulously landscaped backyard. Renewal by Anderson dual pane windows. Guest powder room and laundry downstairs. Upstairs features primary suite, with gorgeous stained glass detail in the master bathroom, as well as all bedrooms and spacious second bathroom with dual sinks. Freshly painted with new flooring this home is turn-key and ready for your finishing touches. Steps away from all the conveniences of shopping, restaurants, groceries and minutes to Highway 101, 280, and 92. Not to mention the great schools. Come make this your home sweet home.",
    yearBuilt: 1978,
    soldDate: "May 5, 2023",
    propertyType: "Single Family",
    mlsLink: "https://www.mlslistings.com/property/sf423727209/1017-avalon-ave-foster-city-ca-94404/15902868",
    mlsNumber: "SF423727209",
    garage: "Attached Garage, Facing Front, Side By Side",
    heating: "Central Forced Air, Gas",
    cooling: "Central Forced Air",
    features: [
      "Vaulted Ceilings",
      "Formal Dining & Living Room",
      "Kitchen/Family Room Combo",
      "Gas Starter Fireplace",
      "Anderson Dual Pane Windows",
      "Stained Glass Detail",
      "Dual Sinks in Bath",
      "Freshly Painted",
      "New Flooring",
      "Turn-Key Ready",
      "Landscaped Backyard",
      "Traditional Style",
    ],
    appliances: [
      "Cooktop - Electric",
      "Oven - Double",
      "Refrigerator",
      "Dryer",
      "Washer",
    ],
  },
];

export function getListings() {
  return listings;
}

export function getListing(id: string) {
  return listings.find((l) => l.id === id);
}

export function formatPrice(price: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(price);
}

export function getRecentListings(count: number = 3) {
  return listings.slice(0, count);
}

// Testimonials data - populated from real client feedback
export const testimonials: Testimonial[] = [];

export function getTestimonials() {
  return testimonials;
}
