import { Listing } from "./types";

// April Zhao's real transactions from MLS
export const listings: Listing[] = [
  {
    id: "1",
    address: "176 Waters Park Cir",
    city: "San Mateo, CA 94403",
    price: 1310000,
    bedrooms: 2,
    bathrooms: 2.5,
    sqft: 1602,
    status: "sold",
    images: [],
    description: "Beautiful townhouse in desirable Waters Park community. Modern finishes throughout with an open floor plan perfect for entertaining.",
    yearBuilt: 2021,
    soldDate: "Dec 22, 2025",
    propertyType: "Townhouse",
  },
  {
    id: "2",
    address: "2042 23rd Ave",
    city: "San Francisco, CA 94116",
    price: 3018000,
    bedrooms: 3,
    bathrooms: 3.5,
    sqft: 2718,
    status: "sold",
    images: [],
    description: "Stunning single family residence in the Sunset District. Spacious layout with modern updates and classic San Francisco charm.",
    yearBuilt: 1941,
    soldDate: "Nov 26, 2025",
    propertyType: "Single Family",
  },
  {
    id: "3",
    address: "1830 Vera Ave",
    city: "Redwood City, CA 94061",
    price: 2220000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 1470,
    status: "sold",
    images: [],
    description: "Charming home on a large lot in a prime Redwood City location. Great potential for expansion or ADU.",
    yearBuilt: 1948,
    soldDate: "Nov 17, 2025",
    propertyType: "Single Family",
  },
  {
    id: "4",
    address: "241 Shelford Ave",
    city: "San Carlos, CA 94070",
    price: 2000000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1780,
    status: "sold",
    images: [],
    description: "Well-maintained home in sought-after San Carlos neighborhood. Close to downtown shops and excellent schools.",
    yearBuilt: 1960,
    soldDate: "Oct 31, 2025",
    propertyType: "Single Family",
  },
  {
    id: "5",
    address: "435 Voelker Dr",
    city: "San Mateo, CA 94403",
    price: 2000000,
    bedrooms: 4,
    bathrooms: 2,
    sqft: 2250,
    status: "sold",
    images: [],
    description: "Spacious single-story home with great curb appeal. Large backyard perfect for outdoor entertaining.",
    yearBuilt: 1953,
    soldDate: "Oct 27, 2025",
    propertyType: "Single Family",
  },
  {
    id: "6",
    address: "1214 North Rd",
    city: "Belmont, CA 94002",
    price: 2528000,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2550,
    status: "sold",
    images: [],
    description: "Beautifully updated home in the Belmont Hills. Panoramic views and premium finishes throughout.",
    yearBuilt: 1977,
    soldDate: "Oct 9, 2025",
    propertyType: "Single Family",
  },
  {
    id: "7",
    address: "3530 Altamont Way",
    city: "Redwood City, CA 94062",
    price: 2266000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1525,
    status: "sold",
    images: [],
    description: "Charming home on a large lot with stunning hillside views. Updated kitchen and bathrooms.",
    yearBuilt: 1960,
    soldDate: "Sep 30, 2025",
    propertyType: "Single Family",
  },
  {
    id: "8",
    address: "2325 Hastings Dr",
    city: "Belmont, CA 94002",
    price: 2308888,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 2210,
    status: "sold",
    images: [],
    description: "Move-in ready home in desirable Belmont location. Spacious living areas and well-manicured yard.",
    yearBuilt: 1977,
    soldDate: "Sep 16, 2025",
    propertyType: "Single Family",
  },
  {
    id: "9",
    address: "1735 Terrace Dr",
    city: "Belmont, CA 94002",
    price: 2600000,
    bedrooms: 5,
    bathrooms: 4,
    sqft: 2800,
    status: "sold",
    images: [],
    description: "Expansive family home with breathtaking Bay views. Multiple living spaces and large lot.",
    yearBuilt: 1956,
    soldDate: "Aug 27, 2025",
    propertyType: "Single Family",
  },
  {
    id: "10",
    address: "2310 Wooster Ave",
    city: "Belmont, CA 94002",
    price: 2300000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 2030,
    status: "sold",
    images: [],
    description: "Classic Belmont home with modern updates. Great neighborhood and top-rated schools.",
    yearBuilt: 1962,
    soldDate: "Aug 19, 2025",
    propertyType: "Single Family",
  },
  {
    id: "11",
    address: "1564 Molitor Rd",
    city: "Belmont, CA 94002",
    price: 2250000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1920,
    status: "sold",
    images: [],
    description: "Character-filled home with vintage charm and modern amenities. Large lot with mature landscaping.",
    yearBuilt: 1929,
    soldDate: "Aug 4, 2025",
    propertyType: "Single Family",
  },
  {
    id: "12",
    address: "631 Spar Dr",
    city: "Redwood City, CA 94065",
    price: 1900000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1080,
    status: "sold",
    images: [],
    description: "Cozy home in Redwood Shores with easy access to tech companies and excellent schools.",
    yearBuilt: 1972,
    soldDate: "May 26, 2025",
    propertyType: "Single Family",
  },
  {
    id: "13",
    address: "721 Taylor Blvd",
    city: "Millbrae, CA 94030",
    price: 2828000,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 2280,
    status: "sold",
    images: [],
    description: "Stunning remodeled home in prime Millbrae location. High-end finishes and open concept design.",
    yearBuilt: 1943,
    soldDate: "May 20, 2025",
    propertyType: "Single Family",
  },
  {
    id: "14",
    address: "1176 Fairview Ave",
    city: "Redwood City, CA 94061",
    price: 2750000,
    bedrooms: 4,
    bathrooms: 3.5,
    sqft: 2010,
    status: "sold",
    images: [],
    description: "Beautifully renovated home in sought-after Mt. Carmel neighborhood. Designer touches throughout.",
    yearBuilt: 1949,
    soldDate: "May 6, 2025",
    propertyType: "Single Family",
  },
  {
    id: "15",
    address: "2850 Belmont Canyon Rd",
    city: "Belmont, CA 94002",
    price: 2950000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2920,
    status: "sold",
    images: [],
    description: "Spectacular hillside home with panoramic views. Modern construction with premium amenities.",
    yearBuilt: 1999,
    soldDate: "Apr 28, 2025",
    propertyType: "Single Family",
  },
  {
    id: "16",
    address: "7 Chestnut St",
    city: "San Carlos, CA 94070",
    price: 2200000,
    bedrooms: 4,
    bathrooms: 2.5,
    sqft: 2870,
    status: "sold",
    images: [],
    description: "Spacious family home in the heart of San Carlos. Walking distance to downtown and Caltrain.",
    yearBuilt: 1979,
    soldDate: "Apr 1, 2025",
    propertyType: "Single Family",
  },
  {
    id: "17",
    address: "503 Sardinia Ter",
    city: "Sunnyvale, CA 94089",
    price: 1780000,
    bedrooms: 3,
    bathrooms: 3.5,
    sqft: 1992,
    status: "sold",
    images: [],
    description: "Modern townhouse in new development. Smart home features and energy-efficient design.",
    yearBuilt: 2020,
    soldDate: "Mar 11, 2025",
    propertyType: "Townhouse",
  },
  {
    id: "18",
    address: "2742 El Sobrante St",
    city: "Santa Clara, CA 95051",
    price: 2200000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1150,
    status: "sold",
    images: [],
    description: "Well-maintained home on a large lot in Santa Clara. Great investment opportunity.",
    yearBuilt: 1956,
    soldDate: "Feb 19, 2025",
    propertyType: "Single Family",
  },
  {
    id: "19",
    address: "1990 Scott Ln",
    city: "Los Altos, CA 94024",
    price: 3800000,
    bedrooms: 4,
    bathrooms: 2.5,
    sqft: 1868,
    status: "sold",
    images: [],
    description: "Prime Los Altos location on a large lot. Excellent Los Altos schools and close to downtown.",
    yearBuilt: 1959,
    soldDate: "Dec 10, 2024",
    propertyType: "Single Family",
  },
  {
    id: "20",
    address: "445 Parrott Dr",
    city: "San Mateo, CA 94402",
    price: 3200000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2020,
    status: "sold",
    images: [],
    description: "Elegant home in prestigious San Mateo Park. Gorgeous remodel with high-end finishes.",
    yearBuilt: 1951,
    soldDate: "Jul 31, 2024",
    propertyType: "Single Family",
  },
  {
    id: "21",
    address: "3 Kimmie Ct",
    city: "Belmont, CA 94002",
    price: 3450000,
    bedrooms: 5,
    bathrooms: 3,
    sqft: 2430,
    status: "sold",
    images: [],
    description: "Stunning family home on a quiet cul-de-sac. Expansive yard and top Belmont schools.",
    yearBuilt: 1967,
    soldDate: "Jul 10, 2024",
    propertyType: "Single Family",
  },
  {
    id: "22",
    address: "1017 Avalon Ave",
    city: "Foster City, CA 94404",
    price: 2120000,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 1910,
    status: "sold",
    images: [],
    description: "Lovely home in family-friendly Foster City. Close to parks, lagoon, and excellent schools.",
    yearBuilt: 1978,
    soldDate: "May 5, 2023",
    propertyType: "Single Family",
  },
];

export function getListings() {
  return listings;
}

export function getListing(id: string) {
  return listings.find((l) => l.id === id);
}

export function formatPrice(price: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(price);
}

export function getRecentListings(count: number = 3) {
  return listings.slice(0, count);
}
